# Generated by Django 5.1.5 on 2025-03-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('origin', models.CharField(max_length=20)),
                ('info', models.TextField()),
            ],
        ),
    ]
