# Generated by Django 5.1.5 on 2025-03-20 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.brand'),
        ),
    ]
